apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: deploy-openshift-
spec:
  pipelineRef:
    name: deploy-openshift
  params:
    - name: cluster
      value: 'magico'
    - name: async
      value: 'false'
    - name: masters
      value: '3'
    - name: workers
      value: '0'
    - name: version
      value: 'stable'
    - name: tag
      value: '4.10'
    - name: network_type
      value: 'OpenShiftSDN'
